version: '3.7'
services:
  pod:
    image: rycus86/podlike
    command: -ipc=false
    labels:
      # sample app with HTML responses
      pod.component.jupyter: |
        image: jupyter/base-notebook
        labels:
          - traefik.enable=true
          - traefik.http.routers.jupyter.rule=hostregexp(`{host:.+}`)
          - traefik.http.routers.jupyter.entrypoints=http
          - traefik.http.services.jupyter.loadbalancer.server.port=8888

      # caching reverse proxy
      pod.component.traefik: |
        image: traefik:v2.1
        command: >
          --entryPoints.http.address=:80
          --accesslog=true
          --log.level=DEBUG
          --providers.docker
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro

      pod.component.alpine-linux: |
        image: alpine:latest
        command: >
          top

    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8080:8080
      - 80:80
