exclude: "^.venv$|^.cache$|^.pytest_cache$"
fail_fast: false
default_language_version:
  python: python3.11
repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v5.0.0
        hooks:
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
        -   id: check-yaml
        -   id: check-added-large-files
        -   id: check-ast
        -   id: check-json
        -   id: check-merge-conflict
        -   id: detect-private-key

    -   repo: https://github.com/psf/black
        rev: 25.1.0
        hooks:
        -   id: black

    -   repo: https://github.com/charliermarsh/ruff-pre-commit
        rev: v0.11.9
        hooks:
        -   id: ruff
            args: [--fix, --exit-non-zero-on-fix]

    -   repo: https://github.com/pycqa/isort
        rev: 6.0.1
        hooks:
        -   id: isort
            args: ["--profile", "black"]


    -   repo: https://github.com/hadolint/hadolint
        rev: v2.13.1-beta
        hooks:
        -   id: hadolint-docker
            name: Lint Dockerfiles

    -   repo: https://github.com/IamTheFij/docker-pre-commit
        rev: v3.0.1
        hooks:
        -   id: docker-compose-check
