version: '3.8'

services:
  simple:
    build:
      context: ./simple
    ports:
      - "8080:8080"
    environment:
      - CPU_LIMIT=2
    deploy:
      resources:
        limits:
          cpus: '2'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  gunicorn:
    build:
      context: ./gunicorn
    ports:
      - "8081:8080"
    environment:
      - CPU_LIMIT=2
    deploy:
      resources:
        limits:
          cpus: '2'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  gunicorn-uvloop:
    build:
      context: ./gunicorn_uvloop
    ports:
      - "8082:8080"
    environment:
      - CPU_LIMIT=2
    deploy:
      resources:
        limits:
          cpus: '2'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
