services:
  prometheus:
    image: prom/prometheus:v2.51.0@sha256:5ccad477d0057e62a7cd1981ffcc43785ac10c5a35522dc207466ff7e7ec845f
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.config.file=/etc/prometheus/web.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.size=1GB"
    ports:
      - 9090:9090
    configs:
      - source: prometheus-config
        target: /etc/prometheus/prometheus.yml
      - source: prometheus-web-config
        target: /etc/prometheus/web.yml
    secrets:
      - source: prometheus-cert
        target: /etc/prometheus/prometheus-cert.pem
      - source: prometheus-key
        target: /etc/prometheus/prometheus-key.pem
    volumes:
      - prometheus-data:/prometheus
      - /var/run/docker.sock:/var/run/docker.sock:ro
    user: root # because of docker
    deploy:
      placement:
        constraints:
          - "node.role==manager"
      resources:
        limits:
          memory: 1024M
          cpus: "1.0"

configs:
  prometheus-config:
    file: ./prometheus.yml
  prometheus-web-config:
    file: ./web.yml
secrets:
  prometheus-cert:
    file: ./.dask-certificates/dask-cert.pem
  prometheus-key:
    file: ./.dask-certificates/dask-key.pem
    
volumes:
  prometheus-data: