version: '3.7'

services:
  prometheus:
    image: prom/prometheus:v2.37.0
    volumes:
      - ./prometheus-dockerswarm.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
    user: root


  redis:
    image: redis:latest


volumes:
  prometheus_data:
