version: '3.8'

services:
  dockerusergroup:
    image: dockerusergroup:prod
    init: true
    user: ${UID}:${GID}
    build:
      context: .
      dockerfile: ./Dockerfile
      target: production
    ports:
      - 8000:8000
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
