version: '3.8'

services:
  dockerusergroup:
    image: dockerusergroup:development
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    # command:
    #   [
    #     "sh",
    #     "-c",
    #     "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn app:app --host 0.0.0.0 --port 8000"
    #   ]
    ports:
      - 8000:8000
      - 5678:5678
    volumes:
      - ./services/app:/app
