version: '3.4'

services:
  dockerusergroup:
    image: dockerusergroup
    init: true
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
